version: "3"
services:
  api: 
    build: ./api
    # comand execute when server start 
    command: npm run start
    # if container down docker compose try restart container
    restart: unless-stopped
    #port which appear outside
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
      - HOST=http://realworld-docker.com
      # any url starts "mongodb" further host "api_db" port "27017" database "api"
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  
  # download image with mongo service
  api_db:
    image: mongo:latest