version: "3"
services:
  api: 
    build: ./api
    # conatainer name 
    container_name: realworld-docker-api
    # comand execute when server start 
    command: npm run start
    # if container down docker compose try restart container
    restart: unless-stopped
    #port which appear outside
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
      - HOST=http://realworld-docker.com
      # any url starts "mongodb" further host "api_db" port "27017" database "api"
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth: 
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db
  

  # download image with mongo service
  api_db:
    image: mongo:latest
    container_name: realworld-docker-api-db
    volumes: 
      - mongodb_api:/data/db

  auth_db: 
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes: 
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth: